# Generated by Django 5.2.4 on 2025-07-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills_offered',
            field=models.ManyToManyField(blank=True, related_name='offered_by', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_wanted',
            field=models.ManyToManyField(blank=True, related_name='wanted_by', to='skills.skill'),
        ),
    ]
